# Generated by Django 3.1 on 2020-10-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('shop', models.TextField()),
                ('img', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField()),
                ('pricing', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('DELIVERY NOT AVAILABLE', 'DELIVERY NOT AVAILABLE'), ('DELIVERY AVAILABLE', 'DELIVERY AVAILABLE')], max_length=200)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('CONFIRMED', 'CONFIRMED')], max_length=200, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mini.create')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mini.prod')),
            ],
        ),
    ]
