# Generated by Django 3.1 on 2020-10-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='img1',
            field=models.ImageField(default='C:Users\\91939\\Pictures', upload_to='pictures'),
        ),
    ]
